export const backgroundImage = {
  position: "absolute",
  left: 0,
  top: 0,
  zIndex: 1,
  display: "block",
  backgroundImage: 'url("app/assets/images/hauntedmansion.jpg")',
  backgroundPosition: "top",
  backgroundRepeat: "no-repeat",
  backgroundSize: "cover",
  width: "100vw",
  height: "100vh",
  WebkitFilter: "brightness(69%) blur(5px)",
  MozFilter: "brightness(69%) blur(5px)",
  OFilter: "brightness(69%) blur(5px)",
  msFilter: "brightness(69%) blur(5px)",
  filter: "brightness(69%) blur(5px)",
};
